name: Sync
on:
  push:
    branches:
      - master

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Sync Master to Release
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "master"
          TO_BRANCH: "release"
          PULL_REQUEST_TITLE: "sync: master to release"
          PULL_REQUEST_BODY: "sync-branches: New code has just landed in master so let's bring release up to speed!"
          PULL_REQUEST_AUTO_MERGE_METHOD: "merge"
          
