name: Sync
on:
  push:
    branches:
      - master

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: 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
          FROM_BRANCH: "master"
          TO_BRANCH: "develop"
          PULL_REQUEST_TITLE: "sync: master to develop"
          PULL_REQUEST_BODY: "sync-branches: New code has just landed in master so let's bring develop up to speed!"
          PULL_REQUEST_AUTO_MERGE_METHOD: "merge:
          
